// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/multiv/v1/multiv.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	types1 "github.com/cosmos/ibc-go/modules/core/02-client/types"
	_ "github.com/cosmos/ibc-go/modules/core/23-commitment/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClientState struct {
	UnderlyingClientState *types.Any `protobuf:"bytes,1,opt,name=underlying_client_state,json=underlyingClientState,proto3" json:"underlying_client_state,omitempty"`
	Depth                 uint32     `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbf389ffd2358a46, []int{0}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return m.Size()
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

type MultiProof struct {
	Head     Proof     `protobuf:"bytes,1,opt,name=head,proto3" json:"head"`
	Branches []Proof   `protobuf:"bytes,2,rep,name=branches,proto3" json:"branches"`
	Leaf     LeafProof `protobuf:"bytes,3,opt,name=leaf,proto3" json:"leaf"`
}

func (m *MultiProof) Reset()         { *m = MultiProof{} }
func (m *MultiProof) String() string { return proto.CompactTextString(m) }
func (*MultiProof) ProtoMessage()    {}
func (*MultiProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbf389ffd2358a46, []int{1}
}
func (m *MultiProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MultiProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MultiProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MultiProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiProof.Merge(m, src)
}
func (m *MultiProof) XXX_Size() int {
	return m.Size()
}
func (m *MultiProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiProof.DiscardUnknown(m)
}

var xxx_messageInfo_MultiProof proto.InternalMessageInfo

type Proof struct {
	ClientProof     []byte        `protobuf:"bytes,1,opt,name=client_proof,json=clientProof,proto3" json:"client_proof,omitempty"`
	ClientState     *types.Any    `protobuf:"bytes,2,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
	ConsensusProof  []byte        `protobuf:"bytes,3,opt,name=consensus_proof,json=consensusProof,proto3" json:"consensus_proof,omitempty"`
	ConsensusState  *types.Any    `protobuf:"bytes,4,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty"`
	ProofHeight     types1.Height `protobuf:"bytes,5,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
	ConsensusHeight types1.Height `protobuf:"bytes,6,opt,name=consensus_height,json=consensusHeight,proto3" json:"consensus_height"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbf389ffd2358a46, []int{2}
}
func (m *Proof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(m, src)
}
func (m *Proof) XXX_Size() int {
	return m.Size()
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

type LeafProof struct {
	Proof       []byte        `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	ProofHeight types1.Height `protobuf:"bytes,2,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
}

func (m *LeafProof) Reset()         { *m = LeafProof{} }
func (m *LeafProof) String() string { return proto.CompactTextString(m) }
func (*LeafProof) ProtoMessage()    {}
func (*LeafProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbf389ffd2358a46, []int{3}
}
func (m *LeafProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LeafProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LeafProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LeafProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeafProof.Merge(m, src)
}
func (m *LeafProof) XXX_Size() int {
	return m.Size()
}
func (m *LeafProof) XXX_DiscardUnknown() {
	xxx_messageInfo_LeafProof.DiscardUnknown(m)
}

var xxx_messageInfo_LeafProof proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.multiv.v1.ClientState")
	proto.RegisterType((*MultiProof)(nil), "ibc.lightclients.multiv.v1.MultiProof")
	proto.RegisterType((*Proof)(nil), "ibc.lightclients.multiv.v1.Proof")
	proto.RegisterType((*LeafProof)(nil), "ibc.lightclients.multiv.v1.LeafProof")
}

func init() {
	proto.RegisterFile("ibc/lightclients/multiv/v1/multiv.proto", fileDescriptor_fbf389ffd2358a46)
}

var fileDescriptor_fbf389ffd2358a46 = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0xaa, 0xd3, 0x40,
	0x18, 0x6d, 0xfa, 0x73, 0xd1, 0x69, 0xfd, 0x21, 0x54, 0xac, 0x5d, 0xa4, 0xbd, 0x17, 0xa4, 0x77,
	0xd3, 0x19, 0xaa, 0x0b, 0x41, 0x11, 0xf1, 0x76, 0xa1, 0xe0, 0x15, 0xa4, 0xee, 0xdc, 0x94, 0x49,
	0x32, 0x4d, 0x06, 0x92, 0x4c, 0x48, 0x26, 0xb5, 0x79, 0x03, 0x97, 0x3e, 0x82, 0x8f, 0x73, 0x97,
	0x77, 0x23, 0xb8, 0x12, 0x69, 0x5f, 0x44, 0x66, 0xbe, 0x69, 0x52, 0x11, 0x8b, 0xba, 0x9b, 0xef,
	0x9b, 0x73, 0xce, 0x77, 0xe6, 0xcc, 0x30, 0x68, 0xc2, 0x5d, 0x8f, 0x44, 0x3c, 0x08, 0xa5, 0x17,
	0x71, 0x96, 0xc8, 0x9c, 0xc4, 0x45, 0x24, 0xf9, 0x9a, 0xac, 0x67, 0x66, 0x85, 0xd3, 0x4c, 0x48,
	0x61, 0x0f, 0xb9, 0xeb, 0xe1, 0x43, 0x20, 0x36, 0xdb, 0xeb, 0xd9, 0xb0, 0x1f, 0x88, 0x40, 0x68,
	0x18, 0x51, 0x2b, 0x60, 0x0c, 0x1f, 0x04, 0x42, 0x04, 0x11, 0x23, 0xba, 0x72, 0x8b, 0x15, 0xa1,
	0x49, 0x69, 0xb6, 0x46, 0x6a, 0xaa, 0x27, 0x32, 0x46, 0x40, 0x4c, 0x4d, 0x83, 0x95, 0x01, 0x4c,
	0x6a, 0x80, 0x88, 0x63, 0x2e, 0xe3, 0x3d, 0xa8, 0xaa, 0x00, 0x78, 0xf6, 0x11, 0x75, 0xe7, 0x9a,
	0xf8, 0x5e, 0x52, 0xc9, 0xec, 0x4b, 0x74, 0xbf, 0x48, 0x7c, 0x96, 0x45, 0x25, 0x4f, 0x82, 0x25,
	0x48, 0x2e, 0x73, 0xb5, 0x35, 0xb0, 0xc6, 0xd6, 0x79, 0xf7, 0x51, 0x1f, 0x83, 0x2b, 0xbc, 0x77,
	0x85, 0x5f, 0x26, 0xe5, 0xe2, 0x5e, 0x4d, 0x3a, 0x54, 0xeb, 0xa3, 0x8e, 0xcf, 0x52, 0x19, 0x0e,
	0x9a, 0x63, 0xeb, 0xfc, 0xd6, 0x02, 0x8a, 0xa7, 0xed, 0x4f, 0x5f, 0x46, 0x8d, 0xb3, 0xaf, 0x16,
	0x42, 0x6f, 0x55, 0x02, 0xef, 0x32, 0x21, 0x56, 0xf6, 0x33, 0xd4, 0x0e, 0x19, 0xf5, 0xcd, 0x94,
	0x53, 0xfc, 0xe7, 0xb4, 0xb0, 0x26, 0x5c, 0xb4, 0xaf, 0xbe, 0x8f, 0x1a, 0x0b, 0x4d, 0xb2, 0xe7,
	0xe8, 0x86, 0x9b, 0xd1, 0xc4, 0x0b, 0x59, 0x3e, 0x68, 0x8e, 0x5b, 0xff, 0x22, 0x50, 0x11, 0xed,
	0x17, 0xa8, 0x1d, 0x31, 0xba, 0x1a, 0xb4, 0xb4, 0x83, 0x87, 0xc7, 0x04, 0x2e, 0x19, 0x5d, 0xfd,
	0xe2, 0x42, 0x11, 0xcd, 0xb9, 0x76, 0x4d, 0xd4, 0x81, 0x23, 0x9d, 0xa2, 0x9e, 0x09, 0x30, 0x55,
	0xb5, 0x3e, 0x5a, 0x6f, 0xd1, 0x85, 0x1e, 0x40, 0x9e, 0x54, 0x10, 0xc8, 0xb8, 0x79, 0x24, 0x63,
	0x43, 0x84, 0x64, 0x27, 0xe8, 0x8e, 0x27, 0x92, 0x9c, 0x25, 0x79, 0x91, 0x1b, 0xf9, 0x96, 0x96,
	0xbf, 0x5d, 0xb5, 0x61, 0xc2, 0xf3, 0x43, 0x20, 0x0c, 0x69, 0x1f, 0x19, 0x52, 0xd3, 0x61, 0xce,
	0x1c, 0xf5, 0xb4, 0xfa, 0x32, 0x64, 0x2a, 0x8a, 0x41, 0x47, 0x73, 0x87, 0x3a, 0x1c, 0xf5, 0xbc,
	0xb0, 0x79, 0x75, 0xeb, 0x19, 0x7e, 0xad, 0x11, 0x26, 0x91, 0xae, 0x66, 0x41, 0xcb, 0x7e, 0x83,
	0xee, 0xd6, 0x1e, 0x8c, 0xd0, 0xc9, 0x5f, 0x0a, 0xd5, 0xee, 0xa1, 0x6d, 0x52, 0x8e, 0xd0, 0xcd,
	0xea, 0x12, 0xd4, 0x33, 0x3b, 0x4c, 0x18, 0x8a, 0xdf, 0xac, 0x37, 0xff, 0xc3, 0x3a, 0x4c, 0xbb,
	0xa0, 0x57, 0x5b, 0xc7, 0xba, 0xde, 0x3a, 0xd6, 0x8f, 0xad, 0x63, 0x7d, 0xde, 0x39, 0x8d, 0xeb,
	0x9d, 0xd3, 0xf8, 0xb6, 0x73, 0x1a, 0x1f, 0x5e, 0x05, 0x5c, 0x86, 0x85, 0x8b, 0x3d, 0x11, 0x13,
	0x9f, 0x4a, 0xea, 0x85, 0x94, 0x27, 0x11, 0x75, 0x09, 0x77, 0xbd, 0x69, 0x9a, 0x89, 0x4d, 0x49,
	0x62, 0xe1, 0x17, 0x11, 0xcb, 0xe1, 0x93, 0x98, 0xee, 0x7f, 0x89, 0xcd, 0x66, 0x6a, 0x3e, 0x0a,
	0x59, 0xa6, 0x2c, 0x77, 0x4f, 0xf4, 0x35, 0x3c, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x82,
	0x72, 0xcb, 0x50, 0x04, 0x00, 0x00,
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Depth != 0 {
		i = encodeVarintMultiv(dAtA, i, uint64(m.Depth))
		i--
		dAtA[i] = 0x10
	}
	if m.UnderlyingClientState != nil {
		{
			size, err := m.UnderlyingClientState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMultiv(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MultiProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MultiProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MultiProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Leaf.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMultiv(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Branches) > 0 {
		for iNdEx := len(m.Branches) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Branches[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMultiv(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Head.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMultiv(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Proof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Proof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ConsensusHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMultiv(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.ProofHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMultiv(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.ConsensusState != nil {
		{
			size, err := m.ConsensusState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMultiv(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.ConsensusProof) > 0 {
		i -= len(m.ConsensusProof)
		copy(dAtA[i:], m.ConsensusProof)
		i = encodeVarintMultiv(dAtA, i, uint64(len(m.ConsensusProof)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ClientState != nil {
		{
			size, err := m.ClientState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMultiv(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientProof) > 0 {
		i -= len(m.ClientProof)
		copy(dAtA[i:], m.ClientProof)
		i = encodeVarintMultiv(dAtA, i, uint64(len(m.ClientProof)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LeafProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LeafProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeafProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ProofHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMultiv(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintMultiv(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMultiv(dAtA []byte, offset int, v uint64) int {
	offset -= sovMultiv(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClientState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UnderlyingClientState != nil {
		l = m.UnderlyingClientState.Size()
		n += 1 + l + sovMultiv(uint64(l))
	}
	if m.Depth != 0 {
		n += 1 + sovMultiv(uint64(m.Depth))
	}
	return n
}

func (m *MultiProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Head.Size()
	n += 1 + l + sovMultiv(uint64(l))
	if len(m.Branches) > 0 {
		for _, e := range m.Branches {
			l = e.Size()
			n += 1 + l + sovMultiv(uint64(l))
		}
	}
	l = m.Leaf.Size()
	n += 1 + l + sovMultiv(uint64(l))
	return n
}

func (m *Proof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientProof)
	if l > 0 {
		n += 1 + l + sovMultiv(uint64(l))
	}
	if m.ClientState != nil {
		l = m.ClientState.Size()
		n += 1 + l + sovMultiv(uint64(l))
	}
	l = len(m.ConsensusProof)
	if l > 0 {
		n += 1 + l + sovMultiv(uint64(l))
	}
	if m.ConsensusState != nil {
		l = m.ConsensusState.Size()
		n += 1 + l + sovMultiv(uint64(l))
	}
	l = m.ProofHeight.Size()
	n += 1 + l + sovMultiv(uint64(l))
	l = m.ConsensusHeight.Size()
	n += 1 + l + sovMultiv(uint64(l))
	return n
}

func (m *LeafProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovMultiv(uint64(l))
	}
	l = m.ProofHeight.Size()
	n += 1 + l + sovMultiv(uint64(l))
	return n
}

func sovMultiv(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMultiv(x uint64) (n int) {
	return sovMultiv(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClientState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMultiv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnderlyingClientState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UnderlyingClientState == nil {
				m.UnderlyingClientState = &types.Any{}
			}
			if err := m.UnderlyingClientState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depth", wireType)
			}
			m.Depth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Depth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMultiv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMultiv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MultiProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMultiv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MultiProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MultiProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Branches", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Branches = append(m.Branches, Proof{})
			if err := m.Branches[len(m.Branches)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaf", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Leaf.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMultiv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMultiv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Proof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMultiv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Proof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Proof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientProof = append(m.ClientProof[:0], dAtA[iNdEx:postIndex]...)
			if m.ClientProof == nil {
				m.ClientProof = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClientState == nil {
				m.ClientState = &types.Any{}
			}
			if err := m.ClientState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsensusProof = append(m.ConsensusProof[:0], dAtA[iNdEx:postIndex]...)
			if m.ConsensusProof == nil {
				m.ConsensusProof = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusState == nil {
				m.ConsensusState = &types.Any{}
			}
			if err := m.ConsensusState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProofHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConsensusHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMultiv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMultiv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LeafProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMultiv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LeafProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LeafProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMultiv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMultiv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProofHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMultiv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMultiv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMultiv(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMultiv
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMultiv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMultiv
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMultiv
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMultiv
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMultiv        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMultiv          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMultiv = fmt.Errorf("proto: unexpected end of group")
)
